name: Update Clash-Core and Go Modules
on:
  repository_dispatch:
    types:
      - core-updated
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Checkout and Update submodules
        run: git submodule update --init --recursive --remote --force

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install update-go-mod-replace
        run: |
          go install github.com/metacubex/update-go-mod-replace@latest

      - name: Update Foss Gomod
        run: |
          cd ${{ github.workspace }}/core/src/foss/golang/
          update-go-mod-replace ${{ github.workspace }}/core/src/foss/golang/clash/go.mod $(pwd)/go.mod
          go mod tidy

      - name: Update Main Gomod
        run: |
          cd ${{ github.workspace }}/core/src/main/golang/
          update-go-mod-replace ${{ github.workspace }}/core/src/foss/golang/clash/go.mod $(pwd)/go.mod
          go mod tidy

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Clash-Meta Core and Go Modules" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
      
